const BOOKS = [
  { name: "Spell Compendium", pdfKey: "Spell Compendium.pdf", indexKey: "spell-compendium-index.json", pdf: "/spell-compendium.pdf", api: "/api/spells", filename: "Spell-Compendium.pdf" },
  { name: "Spell Compendium v2", pdfKey: "Spell Compendium v2.pdf", indexKey: "spell-compendium-v2-index.json", pdf: "/spell-compendium-v2.pdf", api: "/api/spells-v2", filename: "Spell-Compendium-v2.pdf" },
  { name: "Player's Handbook II", pdfKey: "Player's Handbook II spells.pdf", indexKey: "players-handbook-ii-index.json", pdf: "/players-handbook-ii.pdf", api: "/api/players-handbook-ii", filename: "Players-Handbook-II-spells.pdf" },
  { name: "Planar Handbook", pdfKey: "Planar Handbook Spells.pdf", indexKey: "planar-handbook-index.json", pdf: "/planar-handbook.pdf", api: "/api/planar-handbook", filename: "Planar-Handbook-Spells.pdf" },
  { name: "Book of Exalted Deeds", pdfKey: "Book of Exalted Deeds Spells.pdf", indexKey: "book-of-exalted-deeds-index.json", pdf: "/book-of-exalted-deeds.pdf", api: "/api/book-of-exalted-deeds", filename: "Book-of-Exalted-Deeds-Spells.pdf" },
  { name: "Book of Vile Darkness", pdfKey: "Book of Vile Darkness Spells.pdf", indexKey: "book-of-vile-darkness-index.json", pdf: "/book-of-vile-darkness.pdf", api: "/api/book-of-vile-darkness", filename: "Book-of-Vile-Darkness-Spells.pdf" },
  { name: "Miniatures Handbook", pdfKey: "Miniatures Handbook Spells.pdf", indexKey: "miniatures-handbook-index.json", pdf: "/miniatures-handbook.pdf", api: "/api/miniatures-handbook", filename: "Miniatures-Handbook-Spells.pdf" },
];

const SECURITY_HEADERS = {
  "Cache-Control": "private, no-store",
  "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; connect-src 'self'; img-src 'self'; frame-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
  "Referrer-Policy": "no-referrer",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
};

const bookCards = BOOKS.map((book) => `
  <article class="book">
    <h3>${book.name}</h3>
    <p>Personal reference copy · searchable index · PDF</p>
    <a class="button" href="${book.pdf}">Open PDF</a>
  </article>`).join("");
const bookOptions = BOOKS.map((book) =>
  `<option value="${book.name}">${book.name}</option>`
).join("");

const LIBRARY_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Private Rules Library | d20 SRD Hub</title>
<style>
:root{color-scheme:dark;--ink:#e8dcc1;--muted:#b8a98d;--gold:#d7ae5d;--gold-dark:#78582a;--panel:#29231c}*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--ink);background:radial-gradient(circle at top,rgb(122 80 35/28%),transparent 42rem),repeating-linear-gradient(90deg,rgb(255 255 255/2%) 0 1px,transparent 1px 5px),#100e0c;font-family:Georgia,"Times New Roman",serif}header{padding:2.5rem 1.25rem 2rem;text-align:center;border-bottom:1px solid var(--gold-dark);background:linear-gradient(#241d15e8,#15120fee)}header a{color:var(--gold);text-decoration:none}h1{margin:.35rem 0;color:var(--gold);font-size:clamp(2rem,7vw,4rem)}.eyebrow{margin:0;color:var(--muted);letter-spacing:.16em;text-transform:uppercase}main{width:min(1100px,calc(100% - 2rem));margin:3rem auto}.shelf{padding:clamp(1.5rem,5vw,3rem);border:1px solid var(--gold-dark);box-shadow:0 12px 36px #0009,inset 0 0 30px #0004;background:linear-gradient(135deg,#30271e,var(--panel))}h2{margin-top:0;color:var(--gold);font-size:2rem}p{line-height:1.7}.books{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem;margin-top:2rem}.book{display:grid;align-content:start;gap:.6rem;padding:1.35rem;border-left:6px solid #8e3a2b;background:#171411}.book h3{margin:0;color:#f2d48d;font-size:1.3rem}.book p{margin:0;color:var(--muted)}.button{justify-self:start;margin-top:.75rem;padding:.75rem 1.15rem;border:1px solid #b88a3c;color:#21170a;background:linear-gradient(#e3c173,#ad7e31);font-weight:700;text-decoration:none;box-shadow:0 3px 0 #5c401c}.search{margin-top:2rem;padding:1.35rem;border:1px solid var(--gold-dark);background:#171411}.filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.8rem}.search label{display:block;margin-bottom:.4rem;color:#f2d48d;font-weight:700}.search input,.search select{width:100%;padding:.75rem 1rem;border:1px solid var(--gold-dark);border-radius:3px;color:var(--ink);background:#0f0d0b;font:inherit}.query{margin-top:.8rem}.search-status{color:var(--muted)}.results{display:grid;gap:.65rem;padding:0;list-style:none}.result{padding:.85rem 1rem;border-left:4px solid var(--gold-dark);background:#211c17}.result a{color:#f2d48d;font-weight:700}.result-meta{margin:.2rem 0 0;color:var(--muted);font-size:.9rem}footer{margin-top:2rem;color:var(--muted);font-size:.9rem}@media(max-width:760px){.filters{grid-template-columns:1fr 1fr}}@media(max-width:480px){.filters{grid-template-columns:1fr}}
</style></head><body>
<header><p class="eyebrow">d20 SRD Hub</p><h1>Private Rules Library</h1><a href="https://d20srdhub.com/">Return to the public SRD</a></header>
<main><section class="shelf"><h2>Your Bookshelf</h2><p>This private area contains material you purchased for personal reference. It is available only through your protected account.</p>
<div class="books">${bookCards}</div>
<section class="search" aria-labelledby="spell-search-heading"><h3 id="spell-search-heading">Search non-SRD spells</h3><p>Search every private book by source, school, class, or spell level. Results omit spells already available in the public SRD.</p>
<div class="filters"><div><label for="book-filter">Book</label><select id="book-filter"><option value="">All private books</option>${bookOptions}</select></div><div><label for="school-filter">School</label><select id="school-filter"><option value="">All schools</option></select></div><div><label for="class-filter">Class</label><select id="class-filter"><option value="">All classes</option></select></div><div><label for="level-filter">Level</label><select id="level-filter"><option value="">All levels</option></select></div></div>
<div class="query"><label for="spell-search">Spell name or rules metadata</label><input id="spell-search" type="search" autocomplete="off" placeholder="Try: shadow, cleric 3, transmutation"></div>
<p class="search-status" data-search-status>Loading your private spell indexes…</p><ul class="results" data-search-results></ul></section>
<footer>Private personal library · Do not share this address or downloaded files.</footer></section></main><script src="/library.js" defer></script></body></html>`;

const LIBRARY_JS = `
const CLIENT_BOOKS=${JSON.stringify(BOOKS.map(({ name, pdf, api }) => ({ name, pdf, api })))};
const input=document.querySelector("#spell-search"),bookFilter=document.querySelector("#book-filter"),schoolFilter=document.querySelector("#school-filter"),classFilter=document.querySelector("#class-filter"),levelFilter=document.querySelector("#level-filter"),status=document.querySelector("[data-search-status]"),results=document.querySelector("[data-search-results]");let spells=[];
const unique=(values)=>[...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));
function deriveFilters(spell){const classes=[...(spell.classes||[])],levels=[...(spell.spell_levels||[])];for(const part of String(spell.levels||"").split(",")){const match=part.trim().match(/^(.+?)\\s+(\\d+)\\b/);if(match){const aliases={brd:"Bard",clr:"Cleric",drd:"Druid",pal:"Paladin",rgr:"Ranger","sor/wiz":"Sorcerer/Wizard",wiz:"Wizard"};const raw=match[1].trim(),name=aliases[raw.toLowerCase()]||raw.replace(/\\b\\w/g,c=>c.toUpperCase());if(!classes.includes(name))classes.push(name);const level=Number(match[2]);if(!levels.includes(level))levels.push(level)}}return{...spell,classes,spell_levels:levels}}
function addOptions(select,values){for(const value of values){const option=document.createElement("option");option.value=String(value);option.textContent=String(value);select.append(option)}}
function render(){const query=input.value.trim().toLocaleLowerCase(),tokens=query.split(/\\s+/).filter(Boolean),selectedBook=bookFilter.value,selectedSchool=schoolFilter.value,selectedClass=classFilter.value,selectedLevel=levelFilter.value;const matches=spells.filter(spell=>{if(selectedBook&&spell.book!==selectedBook)return false;if(selectedSchool&&spell.school!==selectedSchool)return false;if(selectedClass&&!spell.classes.includes(selectedClass))return false;if(selectedLevel&&!spell.spell_levels.map(String).includes(selectedLevel))return false;const haystack=[spell.name,spell.school,spell.levels,spell.book,...spell.classes,...spell.spell_levels].join(" ").toLocaleLowerCase();return tokens.every(token=>haystack.includes(token))});results.replaceChildren();const visible=matches.slice(0,100);for(const spell of visible){const item=document.createElement("li");item.className="result";const link=document.createElement("a");link.href=spell.pdf+"#page="+spell.page;link.textContent=spell.name;const meta=document.createElement("p");meta.className="result-meta";meta.textContent=[spell.book,spell.school,spell.levels,"PDF page "+spell.page].filter(Boolean).join(" · ");item.append(link,meta);results.append(item)}const filtering=tokens.length||selectedBook||selectedSchool||selectedClass||selectedLevel;if(!filtering)status.textContent=spells.length+" private, non-SRD spells indexed. Search or choose a filter.";else if(!matches.length)status.textContent="No private spells matched your search and filters.";else status.textContent=matches.length+" match"+(matches.length===1?"":"es")+(matches.length>visible.length?"; showing the first "+visible.length:"")+"."}
Promise.all(CLIENT_BOOKS.map(library=>fetch(library.api).then(response=>{if(!response.ok)throw new Error("Spell index unavailable");return response.json().then(payload=>(Array.isArray(payload.spells)?payload.spells:[]).map(spell=>deriveFilters({...spell,book:library.name,pdf:library.pdf}))) }))).then(collections=>{spells=collections.flat();addOptions(schoolFilter,unique(spells.map(s=>s.school)));addOptions(classFilter,unique(spells.flatMap(s=>s.classes)));addOptions(levelFilter,unique(spells.flatMap(s=>s.spell_levels)));render();for(const control of [input,bookFilter,schoolFilter,classFilter,levelFilter])control.addEventListener(control===input?"input":"change",render)}).catch(()=>{status.textContent="One or more private spell indexes are not available yet."});
`;

function securedResponse(body,init={}){const headers=new Headers(init.headers);for(const[name,value]of Object.entries(SECURITY_HEADERS))headers.set(name,value);return new Response(body,{...init,headers})}
function isAuthorized(request,env){const email=request.headers.get("Cf-Access-Authenticated-User-Email")?.trim().toLowerCase();const assertion=request.headers.get("Cf-Access-Jwt-Assertion");return Boolean(assertion)&&Boolean(env.ALLOWED_EMAIL)&&email===env.ALLOWED_EMAIL.trim().toLowerCase()}
async function r2Response(request,env,book,isIndex){const key=isIndex?book.indexKey:book.pdfKey,object=await env.PRIVATE_LIBRARY.get(key);if(!object)return securedResponse(isIndex?'{"error":"Spell index not found"}':"Book not found",{status:isIndex?503:404,headers:{"Content-Type":isIndex?"application/json; charset=utf-8":"text/plain; charset=utf-8"}});const headers={"Content-Length":String(object.size),"Content-Type":isIndex?"application/json; charset=utf-8":"application/pdf"};if(!isIndex)headers["Content-Disposition"]=`inline; filename="${book.filename}"`;return securedResponse(request.method==="HEAD"?null:object.body,{headers})}
export async function handleRequest(request,env){if(!isAuthorized(request,env))return securedResponse("Forbidden",{status:403,headers:{"Content-Type":"text/plain; charset=utf-8"}});const url=new URL(request.url),allowed=request.method==="GET"||request.method==="HEAD";if(url.pathname==="/"&&allowed)return securedResponse(request.method==="HEAD"?null:LIBRARY_HTML,{headers:{"Content-Type":"text/html; charset=utf-8"}});if(url.pathname==="/library.js"&&allowed)return securedResponse(request.method==="HEAD"?null:LIBRARY_JS,{headers:{"Content-Type":"text/javascript; charset=utf-8"}});if(allowed){const indexBook=BOOKS.find(book=>book.api===url.pathname);if(indexBook)return r2Response(request,env,indexBook,true);const pdfBook=BOOKS.find(book=>book.pdf===url.pathname);if(pdfBook)return r2Response(request,env,pdfBook,false)}return securedResponse("Not found",{status:404,headers:{"Content-Type":"text/plain; charset=utf-8"}})}
export default{fetch:handleRequest};
